# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: SelfPool
  demands: Agent.Name -equals cl-ubuntu

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    cd ./api
    npm install
    npm run build
  displayName: 'npm install and build'

- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'Azure subscription 1 (1ff6c602-69fe-454f-a795-de22a178a6c0)'
    appType: 'functionApp'
    appName: 'clapptest0001'
    package: '$(System.DefaultWorkingDirectory)/api/*'
    deploymentMethod: 'auto'
